blog/urls.py
from django.conf.urls import url
from . import views
from .feeds import LatestPostsFeed


urlpatterns = [
    # post views
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    #url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),

    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^feed/$', LatestPostsFeed(), name='post_feed'),
    url(r'^search/$', views.post_search, name='post_search'),
    url(r'^portfolio/$', views.post_portfolio, name='post_portfolio'),
]

myblog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('blog.urls',
                           namespace='blog',
                           app_name='blog')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from embed_video.fields import EmbedVideoField
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset()\
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    image = models.ImageField(upload_to='posts/%Y/%m/%d',
                              blank=True)
    alt_image = models.CharField(max_length=250)
    image_dog = models.ImageField(upload_to='posts/%Y/%m/%d',
                              blank=True)
    alt_image_dog = models.CharField(max_length=250)
    video = EmbedVideoField()
    author = models.ForeignKey(User,
                               related_name='blog_posts')
    body = models.TextField()
    citata = models.TextField()
    anecdot = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.
    tags = TaggableManager()


    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.strftime('%m'),
                             self.publish.strftime('%d'),
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from haystack.query import SearchQuerySet


def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 4) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 4
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags',
                                                                             '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts})





def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    form = SearchForm()
    cd = 0
    results = 0
    total_results = 0
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            results = SearchQuerySet().models(Post).filter(content=cd['query']).load_all()
            # count total results
            total_results = results.count()
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'cd': cd,
                                                     'results': results,
                                                     'total_results': total_results})


def post_portfolio(request):
    return render(request, 'blog/post/portfolio.html')

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static from staticfiles %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="row">

         <div class="col-md-4">

<!--Rotating card-->
            <div class="animated bounceInUp">
<div class="card-wrapper">
    <div id="card-1" class="card-rotating effect__click">

        <!--Front Side-->
        <div class="face front">

            <!-- Image-->
            <div class="card-up">
                <img src="http://mdbootstrap.com/images/reg/reg%20(35).jpg" class="img-fluid">
            </div>
            <!--Avatar-->
            <div class="avatar"><img src="{% static 'img/myphotos/2016-10-28-144519.jpg' %}" class="img-circle img-responsive">
            </div>
            <!--Content-->
            <div class="card-block">
                <h4>Jonathan Doe</h4>
                <p>Web developer</p>
                <!--Triggering button-->
                <a class="rotate-btn" data-card="card-1"><i class="fa fa-repeat"></i> Click here to rotate</a>
            </div>
        </div>
        <!--/.Front Side-->

        <!--Back Side-->
        <div class="face back">

            <!--Content-->


            <h5>My ProjectsGalleryBlog</h5>
        <p>This is my blog. I've written {% total_posts %} posts so far.ssssssssssssssssssssss</p>
  <p><a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a></p>
        <h5>Latest posts</h5>
  {% show_latest_posts 4 %}
      <p></p>

            <hr>
            <!--Social Icons-->

            <!--Triggering button-->
            <a class="rotate-btn" data-card="card-1"><i class="fa fa-undo"></i> Click here to rotate back</a>

        </div>
        <!--/.Back Side-->

    </div>
</div>
            </div>
         </div>

<!--/.Rotating card-->
    <div class="col-md-6">
  <h1>{{ post.title }}</h1>
  <p class="date">
    Published {{ post.publish }} by {{ post.author }}
  </p>
 {{ post.body|markdown }}
    <p>
  <a href="{% url "blog:post_share" post.id %}">
    Share this post
  </a>
</p>
    <h2>Similar posts</h2>
{% for post in similar_posts %}
  <p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </p>
{% empty %}
  There are no similar posts yet.
{% endfor %}
    {% with comments.count as total_comments %}
  <h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
  </h2>
{% endwith %}
    {% for comment in comments %}
  <div class="comment">
    <p class="info">
      Comment {{ forloop.counter }} by {{ comment.name }}
      {{ comment.created }}
    </p>
    {{ comment.body|linebreaks }}
  </div>
{% empty %}
  <p>There are no comments yet.</p>
{% endfor %}
    {% if new_comment %}
  <h2>Your comment has been added.</h2>
{% else %}
  <h2>Add a new comment</h2>

  <form action="." method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}

    <p><button type="submit" class="btn btn-pin">Add Comment</button>
</p>

  </form>
{% endif %}
    </div>
    </div>


{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
{% for post in latest_posts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load embed_video_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
{% for post in posts %}
    <div class="row">

<div class="col-md-4">
    <div class="animated zoomInLeft">
<!--Card-->
<div class="card card-cascade wider">

    <!--Card image-->
    <div class="view overlay hm-white-slight">
        <img src="{{ post.image_dog.url }}" class="img-fluid" alt="{{ post.alt_image }}">
        <a>
            <div class="mask">ddddd</div>
        </a>
    </div>
    <!--/.Card image-->

    <!--Card content-->
    <div class="card-block text-xs-center">
        <!--Category & Title-->
        <h4><a href="{{ post.get_absolute_url }}">Мысли Великих</a></h4>
        <!--Description-->
        <p class="card-text">{{ post.citata }}</p>
    <!--/.Card content-->
</div>
</div>


</div>
</div>
    <div class="col-md-4">
    <div class="embed-responsive embed-responsive-16by9">
    {% video post.video 'small' %}
        </div>

<!--Panel-->
<div class="card card-block">
    <h5 class="card-title">Анекдот дня</h5>
    <p class="card-text">{{ post.anecdot }}</p>

    <a href="#" class="card-link">MyProjectGallery</a>
    <a href="#" class="card-link">Моя ГаллереяПроектов</a>
</div>
<!--/.Panel-->

    </div>
<!--/.Card-->
    <div class="col-md-4">
    <!--Card-->
    <div class="animated zoomInRight">
<div class="card card-cascade wider">

    <!--Card image-->
    <div class="view overlay hm-white-slight">
        <img src="{{ post.image.url }}" class="img-fluid" alt="{{ post.alt_image_dog }}">
        <a>
            <div class="mask">ddddd</div>
        </a>
    </div>
    <!--/.Card image-->

    <!--Card content-->
    <div class="card-block text-xs-center">
        <!--Category & Title-->
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {% if tag %}
        <h4 class="card-title"><strong><a href=""></a></strong></h4>
        {% endif %}
    <p class="tags">

            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}"></a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
         <a href="{{ post.get_absolute_url }}">{{ post.body|markdown|truncatewords_html:10 }}</a>
        <!--Description-->

<div class="chip">
    <img src="http://mdbootstrap.com/images/avatars/img%20(3).jpg" alt="Contact Person">


        <small class="text-muted"><em> {{ post.publish }} by {{ post.author }}</em></small>
</div>



    <!--/.Card content-->
</div>
</div>


</div>
    </div>
    </div>
{% endfor%}

    <p>
    {% include "pagination.html" with page=posts %}</p>


{% endblock %}

blog/templates/blog/post/portfolio.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load static from staticfiles %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}


<!--Card-->
<div class="card testimonial-card">

    <!--Bacground color-->
    <div class="card-up default-color-dark">
    </div>

    <!--Avatar-->
    <div class="avatar"><img src="{% static 'img/myphotos/2016-10-28-144519.jpg' %}">
    </div>

    <div class="card-block">
        <!--Name-->
        <h4 class="card-title">Anna Doe</h4>
        <hr>
        <!--Quotation-->
        <p><i class="fa fa-quote-left"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, adipisci</p>
         <hr class="between-sections">

            <!--Section: Blog v.1-->
            <section class="section extra-margins">

                <!--Section heading-->
                <h1 class="section-heading wow fadeIn" data-wow-delay="0.2s">Blog listing v.1</h1>
                <!--Section sescription-->
                <p class="section-description wow fadeIn" data-wow-delay="0.4s">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit, error amet numquam iure provident voluptate esse quasi, veritatis totam voluptas nostrum quisquam eum porro a pariatur accusamus veniam. Quia, minima?</p>

                <!--First row-->
                <div class="row">

                    <!--First column-->
                    <div class="col-md-5 m-b-r wow fadeInLeft" data-wow-delay="0.2s">
                        <!--Featured image-->
                        <div class="view overlay hm-white-slight">
                            <img src="http://mdbootstrap.com/images/regular/people/img%20(47).jpg">
                            <a>
                                <div class="mask"></div>
                            </a>
                        </div>
                    </div>
                    <!--/First column-->

                    <!--Second column-->
                    <div class="col-md-7 m-b-r wow fadeInRight" data-wow-delay="0.2s">
                        <!--Excerpt-->
                        <h5 class="red-text "><i class="fa fa-fire "></i>Lifestyle</h5>
                        <h4>Top 5 cities for romantic weekend for two.</h4>

<!-- Nav tabs -->
<ul class="nav nav-tabs tabs-2 success-color" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#panel111" role="tab">Русский</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#panel222" role="tab">English</a>
    </li>

</ul>

<!-- Tab panels -->
<div class="tab-content card">

    <!--Panel 1-->
    <div class="tab-pane fade in active" id="panel111" role="tabpanel">
        <br>

        <p>Любовь это ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>

    </div>
    <!--/.Panel 1-->

    <!--Panel 2-->
    <div class="tab-pane fade" id="panel222" role="tabpanel">
        <br>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>

    </div>
    <!--/.Panel 2-->
    </div>

                        <p>by <a><strong>Maria Kate</strong></a>, 23.06.2016</p>
                        <a class="btn btn-primary ">Read more</a>
                    </div>
                    <!--/Second column-->


                <!--/First row-->

                <hr>

                <!--Second row-->
                <div class="row">

                    <!--First column-->
                    <div class="col-md-7 m-b-r wow fadeInLeft" data-wow-delay="0.3s">
                        <!--Excerpt-->
                        <h5 class="blue-text "><i class="fa fa-trophy "></i>Sport</h5>
                        <h4>What you need to know before begin workout.</h4>

<!-- Nav tabs -->
<ul class="nav nav-tabs tabs-2 default-color
" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#panel10" role="tab">Русский</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#panel20" role="tab">English</a>
    </li>

</ul>

<!-- Tab panels -->
<div class="tab-content card">

    <!--Panel 1-->
    <div class="tab-pane fade in active" id="panel10" role="tabpanel">
        <br>

        <p>Любовь это ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>

    </div>
    <!--/.Panel 1-->

    <!--Panel 2-->
    <div class="tab-pane fade" id="panel20" role="tabpanel">
        <br>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>

    </div>
    <!--/.Panel 2-->
    </div>

                        <p>by <a><strong>John Doe</strong></a>, 22.06.2016</p>
                        <a class="btn btn-primary ">Read more</a>
                    </div>

                    <!--/First column-->

                    <!--Second column-->
                    <div class="col-md-5 m-b-r wow fadeInRight" data-wow-delay="0.3s">
                        <!--Featured image-->
                        <div class="view overlay hm-white-slight">
                            <img src="http://mdbootstrap.com/images/regular/people/img%20(48).jpg">
                            <a>
                                <div class="mask"></div>
                            </a>
                        </div>
                    </div>
                    <!--/Second column-->

                </div>
                <!--/Second row-->

                <hr>

                <!--Third row-->
                <div class="row">

                    <!--First column-->
                    <div class="col-md-5 m-b-r wow fadeInLeft" data-wow-delay="0.4s">
                        <!--Featured image-->
                        <div class="view overlay hm-white-slight">
                            <img src="http://mdbootstrap.com/images/regular/people/img%20(49).jpg">
                            <a>
                                <div class="mask"></div>
                            </a>
                        </div>
                    </div>
                    <!--/First column-->

                    <!--Second column-->
                    <div class="col-md-7 m-b-r wow fadeInRight" data-wow-delay="0.4s">
                        <!--Excerpt-->
                        <h5 class="teal-text "><i class="fa fa-television "></i>Entertainment</h5>
                        <h4>My best summer adventure - Glastonbury Festival.</h4>

<!-- Nav tabs -->
<ul class="nav nav-tabs tabs-2 warning-color" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" data-toggle="tab" href="#panel11" role="tab">Русский</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">English</a>
    </li>

</ul>

<!-- Tab panels -->
<div class="tab-content card">

    <!--Panel 1-->
    <div class="tab-pane fade in active" id="panel11" role="tabpanel">
        <br>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>

    </div>
    <!--/.Panel 1-->

    <!--Panel 2-->
    <div class="tab-pane fade" id="panel22" role="tabpanel">
        <br>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nihil odit magnam minima, soluta doloribus reiciendis molestiae placeat unde eos molestias. Quisquam aperiam, pariatur. Tempora, placeat ratione porro voluptate odit minima.</p>

    </div>
    <!--/.Panel 2-->


</div>

                        <p>by <a><strong>Maria Kate</strong></a>, 21.06.2016</p>
                        <a class="btn btn-primary ">Read more</a>
                    </div>
                    <!--/Second column-->

                </div>
                <!--/Third row-->
</div>
            </section>
            <!--/Section: Blog v.1-->

            <hr class="between-sections">
    </div>

</div>
<!--/.Card-->



{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if "query" in request.GET %}
    <h1>Posts containing "{{ cd.query }}"</h1>
    <h3>Found {{ total_results }} result{{ total_results|pluralize }}</h3>
    {% for result in results %}
      {% with post=result.object %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
      {% endwith %}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "blog:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
  {% if sent %}
    <h1>E-mail successfully sent</h1>
    <p>
      "{{ post.title }}" was successfully sent to {{ cd.to }}.
    </p>
  {% else %}
    <h1>Share "{{ post.title }}" by e-mail</h1>
    <form action="." method="post">
      {{ form.as_p }}
      {% csrf_token %}
      <input type="submit" value="Send e-mail">
    </form>
  {% endif %}
{% endblock %}